eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      statusPageUrlPath: ${management.contextPath}/info
      healthCheckUrlPath: ${management.contextPath}/health
      hostname: ${vcap.application.uris[0]}
      nonSecurePort: 80
      metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}